// AxTIF5.idl : ActiveX コントロール プロジェクトのタイプ ライブラリ ソースです。

// このファイルは、AxTIF5.ocx のリソース
// になるタイプ ライブラリ (AxTIF5.tlb) を作成するために MIDL コンパイラ ツール
// によって処理されます。

#include <olectl.h>
#include <idispids.h>

[ uuid(3C358B7C-A227-42C7-A226-89C5CDD692C6), version(1.0),
  helpfile("AxTIF5.hlp"),
  helpstring("AxTIF5 ActiveX コントロール モジュール"),
  control ]
library AxTIF5Lib
{
	importlib(STDOLE_TLB);

	//  CAxTIF5Ctrl のプライマリ ディスパッチ インターフェイスです。

	[ uuid(56EC6F0A-34F6-4D86-9695-7B1E6FB61898),
	  helpstring("AxTIF5 Control のディスパッチ インターフェイスです。")]
	dispinterface _DAxTIF5
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
	};

	//  CAxTIF5Ctrl のイベント ディスパッチ インターフェイスです。

	[ uuid(CCBC4D8D-1D02-4CD2-9ED0-F96BDD8C4A69),
	  helpstring("AxTIF5 Control のイベント インターフェイスです。") ]
	dispinterface _DAxTIF5Events
	{
		properties:
			//  イベント インターフェイスにプロパティがありません。

		methods:
	};

	//  CAxTIF5Ctrl のクラス情報です。

	[ uuid(05936E26-30E9-4210-84A6-A059B4512D14),
	  helpstring("AxTIF5 Control"), control ]
	coclass AxTIF5
	{
		[default] dispinterface _DAxTIF5;
		[default, source] dispinterface _DAxTIF5Events;
	};

};
