// Noime4ntr.idl : Noime4ntr の IDL ソース
//

// このファイルは、タイプ ライブラリ (Noime4ntr.tlb) およびマーシャリング コードを
// 作成するために MIDL ツールによって処理されます。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(EFC4506F-AD56-4D56-B248-93FE07FB37CC),
	dual,
	nonextensible,
	helpstring("ICloser インターフェイス"),
	pointer_default(unique)
]
interface ICloser : IDispatch{
	[id(252), helpstring("メソッド NavigateComplete2"), hidden] HRESULT NavigateComplete2([in] IDispatch* pDisp, [in] VARIANT* URL);
};
[
	uuid(9EAF3694-AC41-4559-976F-F4B1D66FC039),
	version(1.0),
	helpstring("Noime4ntr 1.0 タイプ ライブラリ")
]
library Noime4ntrLib
{
	importlib("stdole2.tlb");
	[
		uuid(3A01783B-18FE-494F-AAEA-914B34CD5844),
		helpstring("Closer Class")
	]
	coclass Closer
	{
		[default] interface ICloser;
	};
};
