// IEView.idl : IEView.exe のタイプ ライブラリ ソース

// このファイルは、タイプ ライブラリ (IEView.tlb) を作成するために、
// MIDL コンパイラによって処理されます。

[ uuid(FE4D822C-9BFC-451E-9499-DA5DC9FF3B1E), version(1.0) ]
library IEView
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CDoc のプライマリ ディスパッチ インターフェイス
	
	[ uuid(30057643-DF70-4AC3-BF00-1CE1192DF309) ]
	dispinterface IIEView
	{
		properties:
			
		methods:
	};

	//  CDoc のクラス情報
	
	[ uuid(6B8B1B23-FE04-4308-999A-B5E7064E849F) ]
	coclass CDoc
	{
		[default] dispinterface IIEView;
	};
};
